### ISSUE TITLE
Create docs based on the slides

### ISSUE THREAD

**Issue by ocefpaf** [ioos/ioos-python-package-skeleton#1]
- [x] add some of the code sprint presentation content to the README to explain its purpose better;
- [x] create a github.io page/docs built with sphinx with the contents, that will demonstrate the documentation auto-build and keep the contentes in a readable form.

**Comment by ocefpaf** [comment]
Add docs on how to create an auto-deployment for PyPI:

- create a conda ruby environment and install Travis-CI CLI

```shell
conda create --name RUBY rb-bundler compilers
conda activate RUBY
gem install travis --no-rdoc --no-ri
```

- [login on your PyPI account](https://pypi.org/manage/account/token/) and create a limited scope (upload for a single project) token

- encrypt the token with Travis-CI CLI tool:

```
travis encrypt "<your-token-here>"
```

- add the following lines to your `.travis.yml` file:

```yaml
deploy:
  skip_cleanup: true
  provider: pypi
  user: "__token__"
  password:
    secure: "results-from-the-command-above"  # add the encrypted token here
  distributions: sdist bdist_wheel
  upload_docs: no
  on:
    repo: org/repo  # change here for your project
    tags: true
    all_branches: master
    condition: '$TRAVIS_JOB_NAME == "docs"'  # publish on a job named docs, adapt according to your Travis-CI configuration.
```
